manifest:
  version: '0.12'
  remotes:
  - name: rnl
    url-base: https://github.com/rednodelabs
  - name: ncs
    url-base: https://github.com/nrfconnect
  defaults:
    remote: rnl
  projects:
  - name: nrf
    repo-path: sdk-nrf
    revision: v2.1.0
    remote: ncs
    import:
      name-blocklist:
      - zephyr
      - openthread
  - name: zephyr
    revision: rednodelabs/v1.0.1
    import:
      name-allowlist:
      - TraceRecorderSource
      - canopennode
      - chre
      - cmsis
      - edtt
      - fatfs
      - fff
      - hal_nordic
      - hal_st
      - liblc3codec
      - libmetal
      - littlefs
      - loramac-node
      - lvgl
      - lz4
      - mbedtls
      - mipi-sys-t
      - nanopb
      - net-tools
      - nrf_hw_models
      - open-amp
      - picolibc
      - psa-arch-tests
      - segger
      - tinycbor
      - tinycrypt
      - tf-m-tests
      - zcbor
      - zscilib
  - name: openthread
    path: modules/lib/openthread
    revision: rednodelabs/v1.0.5
  - name: rednodebus-release
    revision: v1.0.10
  self:
    west-commands: nrf/scripts/west-commands.yml
