/* socket-test.c - Networking UDP socket client */

/*
 * Copyright (c) 2022 RedNodeLabs UG.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/*
 * The socket-test application is acting as a client that is run in Zephyr OS,
 * and the server is run in the host acting as a server.
 */

#include <logging/log.h>
LOG_MODULE_REGISTER(net_socket_test_sample, LOG_LEVEL_DBG);

#include <zephyr.h>
#include <errno.h>
#include <stdio.h>

#include <syscalls/rand32.h>
#include <net/socket.h>
#include <net/net_mgmt.h>
#include <net/net_event.h>
#include <net/net_conn_mgr.h>
#include <net/ieee802154_radio.h>

#ifdef CONFIG_REDNODEBUS
#include "rnb_utils.h"
#endif /* CONFIG_REDNODEBUS */

#include "common.h"

#define INVALID_SOCK (-1)

#define EVENT_MASK (NET_EVENT_L4_CONNECTED | \
		    NET_EVENT_L4_DISCONNECTED)

#define MTU_SIZE 1280

static uint8_t rnb_role;

void rnb_utils_handle_new_state(const struct rednodebus_user_event_state *event_state)
{
	rnb_role = event_state->role;
}

/* Generated by http://www.lipsum.com/
 * 2 paragraphs, 179 words, 1160 bytes of Lorem Ipsum
 */
char lorem_ipsum[] =
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque "
    "sodales lorem lorem, sed congue enim vehicula a. Sed finibus diam sed "
    "odio ultrices pharetra. Nullam dictum arcu ultricies turpis congue, "
    "vel venenatis turpis venenatis. Nam tempus arcu eros, ac congue libero "
    "tristique congue. Proin velit lectus, euismod sit amet quam in, "
    "maximus condimentum urna. Cras vel erat luctus, mattis orci ut, varius "
    "urna. Nam eu lobortis velit."
    "\n"
    "Nullam sit amet diam vel odio sodales cursus vehicula eu arcu. Proin "
    "fringilla, enim nec consectetur mollis, lorem orci interdum nisi, "
    "vitae suscipit nisi mauris eu mi. Proin diam enim, mollis ac rhoncus "
    "vitae, placerat et eros. Suspendisse convallis, ipsum nec rhoncus "
    "aliquam, ex augue ultrices nisl, id aliquet mi diam quis ante. "
    "Pellentesque venenatis ornare ultrices. Quisque et porttitor lectus. "
    "Ut venenatis nunc et urna imperdiet porttitor non laoreet massa. Donec "
    "eleifend eros in mi sagittis egestas. Sed et mi nunc. Nunc vulputate, "
    "mauris non ullamcorper viverra, lorem nulla vulputate diam, et congue "
    "dui velit non erat. Duis interdum leo et ipsum tempor consequat. In "
    "faucibus enim quis purus vulputate nullam."
    "\n";

const int ipsum_len = sizeof(lorem_ipsum) - 1;

struct configs conf = {
    .ipv6 = {
	.proto = "IPv6",
	.udp.sock = INVALID_SOCK},
};

static void init_app(void)
{
	conf.ipv6.udp.mtu = MTU_SIZE;

#if defined(CONFIG_REDNODEBUS)
	uint64_t euid = 0;
	rnb_utils_get_euid(&euid);

	sprintf(lorem_ipsum, "%04X%04X", (uint32_t)(euid >> 32), (uint32_t)euid);

	int session_rand = sys_rand32_get();
	memcpy(&lorem_ipsum[UID_CHARS], &session_rand, sizeof(session_rand));
#endif
}

static int start_client(void)
{
	int iterations = 0;
	int i = 0;
	int ret;

	while (iterations == 0 || i < iterations)
	{
		ret = start_udp();

		while (ret == 0)
		{
			send_udp_data(&conf.ipv6);

			if (iterations > 0)
			{
				i++;
				if (i >= iterations)
				{
					break;
				}
			}
			if (rnb_role == REDNODEBUS_USER_ROLE_TAG)
			{
				k_sleep(K_MSEC(UDP_TRANSMISSION_PERIOD_TAG_MSEC));
			}
			else
			{
				k_sleep(K_MSEC(UDP_TRANSMISSION_PERIOD_MSEC));
			}
		}
		stop_udp();
	}
	return ret;
}

void main(void)
{
#ifdef CONFIG_REDNODEBUS
	init_rnb();

	while (!is_rnb_connected())
	{
		k_sleep(K_MSEC(1000));
	}

	k_sleep(K_MSEC(1000));
#endif /* CONFIG_REDNODEBUS */

	init_app();

	k_thread_priority_set(k_current_get(), THREAD_PRIORITY);

	exit(start_client());
}
